name: analysis2
channels:
  - conda-forge
  - bioconda
dependencies:
  - gcc
  - gmp
  - gxx
  - mpfr
  - pip
  - slim==3.7.1
  - snakemake>=7.9.0
  - ldc
  - seaborn
  - pysam
  - htslib
  - scipy
  - numpy
  - matplotlib
  - attrs
  - cython
  - tqdm
  - h5py
  - gfortran
  - blas
  - gsl
  - dadi
  - mamba
  - openjdk
  - pip:
    - git+https://github.com/popsim-consortium/stdpopsim.git
    - scikit-allel
    - git+https://github.com/xin-huang/dadi-cli
